void Quenched()
{
//=========Macro generated from canvas: c/c
//=========  (Mon Nov  7 00:13:55 2022) by ROOT version 6.24/06
   TCanvas *c = new TCanvas("c", "c",1380,63,1000,1002);
   c->Range(0.009958907,-1.229138,1.671282,5.729334);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetLogx();
   c->SetLogy();
   c->SetFrameBorderMode(0);
   c->SetFrameBorderMode(0);
   
   TH1D *QLeadingParticlePt__1 = new TH1D("QLeadingParticlePt__1","Leading v Subleading p_{T} (Quenching)",100,0,50);
   QLeadingParticlePt__1->SetBinContent(4,394);
   QLeadingParticlePt__1->SetBinContent(5,13325);
   QLeadingParticlePt__1->SetBinContent(6,51900);
   QLeadingParticlePt__1->SetBinContent(7,56770);
   QLeadingParticlePt__1->SetBinContent(8,35932);
   QLeadingParticlePt__1->SetBinContent(9,19284);
   QLeadingParticlePt__1->SetBinContent(10,10000);
   QLeadingParticlePt__1->SetBinContent(11,5419);
   QLeadingParticlePt__1->SetBinContent(12,2714);
   QLeadingParticlePt__1->SetBinContent(13,1694);
   QLeadingParticlePt__1->SetBinContent(14,1107);
   QLeadingParticlePt__1->SetBinContent(15,700);
   QLeadingParticlePt__1->SetBinContent(16,500);
   QLeadingParticlePt__1->SetBinContent(17,277);
   QLeadingParticlePt__1->SetBinContent(18,207);
   QLeadingParticlePt__1->SetBinContent(19,191);
   QLeadingParticlePt__1->SetBinContent(20,68);
   QLeadingParticlePt__1->SetBinContent(21,67);
   QLeadingParticlePt__1->SetBinContent(22,28);
   QLeadingParticlePt__1->SetBinContent(23,32);
   QLeadingParticlePt__1->SetBinContent(24,45);
   QLeadingParticlePt__1->SetBinContent(25,24);
   QLeadingParticlePt__1->SetBinContent(26,29);
   QLeadingParticlePt__1->SetBinContent(27,7);
   QLeadingParticlePt__1->SetBinContent(28,29);
   QLeadingParticlePt__1->SetBinContent(29,12);
   QLeadingParticlePt__1->SetBinContent(30,8);
   QLeadingParticlePt__1->SetBinContent(31,18);
   QLeadingParticlePt__1->SetBinContent(32,5);
   QLeadingParticlePt__1->SetBinContent(33,1);
   QLeadingParticlePt__1->SetBinContent(37,7);
   QLeadingParticlePt__1->SetBinContent(40,2);
   QLeadingParticlePt__1->SetBinContent(41,3);
   QLeadingParticlePt__1->SetEntries(200799);
   QLeadingParticlePt__1->Scale(1./QLeadingParticlePt__1->Integral());
   
   TPaveStats *Qptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   Qptstats->SetName("stats");
   Qptstats->SetBorderSize(1);
   Qptstats->SetFillColor(0);
   Qptstats->SetTextAlign(12);
   Qptstats->SetTextFont(42);
   TText *Qptstats_LaTex = Qptstats->AddText("LeadingParticlePt");
   Qptstats_LaTex->SetTextSize(0.0368);
   Qptstats_LaTex = Qptstats->AddText("Entries = 200799 ");
   Qptstats_LaTex = Qptstats->AddText("Mean  =  3.504");
   Qptstats_LaTex = Qptstats->AddText("Std Dev   =  1.009");
   Qptstats->SetOptStat(1111);
   Qptstats->SetOptFit(0);
   Qptstats->Draw();
   QLeadingParticlePt__1->GetListOfFunctions()->Add(Qptstats);
   Qptstats->SetParent(QLeadingParticlePt__1);
   QLeadingParticlePt__1->SetLineColor(2);
   QLeadingParticlePt__1->SetMarkerColor(2);
   QLeadingParticlePt__1->SetMarkerStyle(20);
   QLeadingParticlePt__1->GetXaxis()->SetRange(4,64);
   QLeadingParticlePt__1->GetXaxis()->SetLabelFont(42);
   QLeadingParticlePt__1->GetXaxis()->SetTitleOffset(1);
   QLeadingParticlePt__1->GetXaxis()->SetTitleFont(42);
   QLeadingParticlePt__1->GetYaxis()->SetLabelFont(42);
   QLeadingParticlePt__1->GetYaxis()->SetTitleFont(42);
   QLeadingParticlePt__1->GetZaxis()->SetLabelFont(42);
   QLeadingParticlePt__1->GetZaxis()->SetTitleOffset(1);
   QLeadingParticlePt__1->GetZaxis()->SetTitleFont(42);
   QLeadingParticlePt__1->Draw("EP");
   
   TH1D *QSubLeadingParticlePt__2 = new TH1D("QSubLeadingParticlePt__2","Sub Leading Particle pT",100,0,50);
   QSubLeadingParticlePt__2->SetBinContent(4,1803);
   QSubLeadingParticlePt__2->SetBinContent(5,39321);
   QSubLeadingParticlePt__2->SetBinContent(6,80423);
   QSubLeadingParticlePt__2->SetBinContent(7,47259);
   QSubLeadingParticlePt__2->SetBinContent(8,18373);
   QSubLeadingParticlePt__2->SetBinContent(9,7208);
   QSubLeadingParticlePt__2->SetBinContent(10,2802);
   QSubLeadingParticlePt__2->SetBinContent(11,1374);
   QSubLeadingParticlePt__2->SetBinContent(12,841);
   QSubLeadingParticlePt__2->SetBinContent(13,425);
   QSubLeadingParticlePt__2->SetBinContent(14,315);
   QSubLeadingParticlePt__2->SetBinContent(15,219);
   QSubLeadingParticlePt__2->SetBinContent(16,145);
   QSubLeadingParticlePt__2->SetBinContent(17,81);
   QSubLeadingParticlePt__2->SetBinContent(18,51);
   QSubLeadingParticlePt__2->SetBinContent(19,50);
   QSubLeadingParticlePt__2->SetBinContent(20,11);
   QSubLeadingParticlePt__2->SetBinContent(21,15);
   QSubLeadingParticlePt__2->SetBinContent(22,26);
   QSubLeadingParticlePt__2->SetBinContent(23,5);
   QSubLeadingParticlePt__2->SetBinContent(24,6);
   QSubLeadingParticlePt__2->SetBinContent(25,16);
   QSubLeadingParticlePt__2->SetBinContent(26,4);
   QSubLeadingParticlePt__2->SetBinContent(27,11);
   QSubLeadingParticlePt__2->SetBinContent(30,4);
   QSubLeadingParticlePt__2->SetBinContent(32,5);
   QSubLeadingParticlePt__2->SetBinContent(33,1);
   QSubLeadingParticlePt__2->SetBinContent(37,4);
   QSubLeadingParticlePt__2->SetBinContent(41,1);
   QSubLeadingParticlePt__2->SetEntries(200799);

   QSubLeadingParticlePt__2->Scale(1./QSubLeadingParticlePt__2->Integral());
   QSubLeadingParticlePt__2->SetMarkerStyle(20);
   QSubLeadingParticlePt__2->GetXaxis()->SetRange(4,64);
   QSubLeadingParticlePt__2->GetXaxis()->SetLabelFont(42);
   QSubLeadingParticlePt__2->GetXaxis()->SetTitleOffset(1);
   QSubLeadingParticlePt__2->GetXaxis()->SetTitleFont(42);
   QSubLeadingParticlePt__2->GetYaxis()->SetLabelFont(42);
   QSubLeadingParticlePt__2->GetYaxis()->SetTitleFont(42);
   QSubLeadingParticlePt__2->GetZaxis()->SetLabelFont(42);
   QSubLeadingParticlePt__2->GetZaxis()->SetTitleOffset(1);
   QSubLeadingParticlePt__2->GetZaxis()->SetTitleFont(42);
   QSubLeadingParticlePt__2->Draw("EP SAME");
   
   TPaveText *Qpt = new TPaveText(0.1513026,0.9097436,0.8517034,0.9692308,"blNDC");
   Qpt->SetName("title");
   Qpt->SetBorderSize(0);
   Qpt->SetFillColor(0);
   Qpt->SetFillStyle(0);
   Qpt->SetTextFont(42);
   Qpt->SetTextSize(0.02051282);
   TText *Qpt_LaTex = Qpt->AddText("Leading v Subleading p_{T} (Quenching)");
   Qpt->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);

   TH1D *LeadingParticlePt__1 = new TH1D("LeadingParticlePt__1","Leading v Subleading p_{T} (No Quenching)",100,0,50);
   LeadingParticlePt__1->SetBinContent(4,75);
   LeadingParticlePt__1->SetBinContent(5,4900);
   LeadingParticlePt__1->SetBinContent(6,24332);
   LeadingParticlePt__1->SetBinContent(7,39819);
   LeadingParticlePt__1->SetBinContent(8,38959);
   LeadingParticlePt__1->SetBinContent(9,29232);
   LeadingParticlePt__1->SetBinContent(10,20466);
   LeadingParticlePt__1->SetBinContent(11,13754);
   LeadingParticlePt__1->SetBinContent(12,9433);
   LeadingParticlePt__1->SetBinContent(13,5858);
   LeadingParticlePt__1->SetBinContent(14,3960);
   LeadingParticlePt__1->SetBinContent(15,2795);
   LeadingParticlePt__1->SetBinContent(16,1899);
   LeadingParticlePt__1->SetBinContent(17,1299);
   LeadingParticlePt__1->SetBinContent(18,893);
   LeadingParticlePt__1->SetBinContent(19,634);
   LeadingParticlePt__1->SetBinContent(20,459);
   LeadingParticlePt__1->SetBinContent(21,323);
   LeadingParticlePt__1->SetBinContent(22,226);
   LeadingParticlePt__1->SetBinContent(23,135);
   LeadingParticlePt__1->SetBinContent(24,143);
   LeadingParticlePt__1->SetBinContent(25,122);
   LeadingParticlePt__1->SetBinContent(26,37);
   LeadingParticlePt__1->SetBinContent(27,42);
   LeadingParticlePt__1->SetBinContent(28,46);
   LeadingParticlePt__1->SetBinContent(29,29);
   LeadingParticlePt__1->SetBinContent(30,13);
   LeadingParticlePt__1->SetBinContent(31,24);
   LeadingParticlePt__1->SetBinContent(32,23);
   LeadingParticlePt__1->SetBinContent(33,3);
   LeadingParticlePt__1->SetBinContent(34,15);
   LeadingParticlePt__1->SetBinContent(35,13);
   LeadingParticlePt__1->SetBinContent(36,10);
   LeadingParticlePt__1->SetBinContent(37,11);
   LeadingParticlePt__1->SetBinContent(38,1);
   LeadingParticlePt__1->SetBinContent(42,2);
   LeadingParticlePt__1->SetBinContent(48,1);
   LeadingParticlePt__1->SetBinContent(50,8);
   LeadingParticlePt__1->SetBinContent(57,1);
   LeadingParticlePt__1->SetEntries(199995);
   LeadingParticlePt__1->Scale(1./LeadingParticlePt__1->Integral());
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *ptstats_LaTex = ptstats->AddText("LeadingParticlePt");
   ptstats_LaTex->SetTextSize(0.0368);
   ptstats_LaTex = ptstats->AddText("Entries = 199995 ");
   ptstats_LaTex = ptstats->AddText("Mean  =  4.217");
   ptstats_LaTex = ptstats->AddText("Std Dev   =  1.428");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   LeadingParticlePt__1->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(LeadingParticlePt__1);
   LeadingParticlePt__1->SetLineColor(2);
   LeadingParticlePt__1->SetMarkerColor(2);
   LeadingParticlePt__1->SetMarkerStyle(24);
   LeadingParticlePt__1->GetXaxis()->SetRange(4,64);
   LeadingParticlePt__1->GetXaxis()->SetLabelFont(42);
   LeadingParticlePt__1->GetXaxis()->SetTitleOffset(1);
   LeadingParticlePt__1->GetXaxis()->SetTitleFont(42);
   LeadingParticlePt__1->GetYaxis()->SetLabelFont(42);
   LeadingParticlePt__1->GetYaxis()->SetTitleFont(42);
   LeadingParticlePt__1->GetZaxis()->SetLabelFont(42);
   LeadingParticlePt__1->GetZaxis()->SetTitleOffset(1);
   LeadingParticlePt__1->GetZaxis()->SetTitleFont(42);
   LeadingParticlePt__1->Draw("EP SAME");
   
   TH1D *SubLeadingParticlePt__2 = new TH1D("SubLeadingParticlePt__2","Sub Leading Particle pT",100,0,50);
   SubLeadingParticlePt__2->SetBinContent(4,471);
   SubLeadingParticlePt__2->SetBinContent(5,15935);
   SubLeadingParticlePt__2->SetBinContent(6,50437);
   SubLeadingParticlePt__2->SetBinContent(7,53497);
   SubLeadingParticlePt__2->SetBinContent(8,33911);
   SubLeadingParticlePt__2->SetBinContent(9,19456);
   SubLeadingParticlePt__2->SetBinContent(10,10062);
   SubLeadingParticlePt__2->SetBinContent(11,6343);
   SubLeadingParticlePt__2->SetBinContent(12,3419);
   SubLeadingParticlePt__2->SetBinContent(13,2159);
   SubLeadingParticlePt__2->SetBinContent(14,1453);
   SubLeadingParticlePt__2->SetBinContent(15,938);
   SubLeadingParticlePt__2->SetBinContent(16,520);
   SubLeadingParticlePt__2->SetBinContent(17,420);
   SubLeadingParticlePt__2->SetBinContent(18,290);
   SubLeadingParticlePt__2->SetBinContent(19,128);
   SubLeadingParticlePt__2->SetBinContent(20,162);
   SubLeadingParticlePt__2->SetBinContent(21,90);
   SubLeadingParticlePt__2->SetBinContent(22,71);
   SubLeadingParticlePt__2->SetBinContent(23,28);
   SubLeadingParticlePt__2->SetBinContent(24,51);
   SubLeadingParticlePt__2->SetBinContent(25,34);
   SubLeadingParticlePt__2->SetBinContent(26,14);
   SubLeadingParticlePt__2->SetBinContent(27,19);
   SubLeadingParticlePt__2->SetBinContent(28,25);
   SubLeadingParticlePt__2->SetBinContent(29,7);
   SubLeadingParticlePt__2->SetBinContent(30,13);
   SubLeadingParticlePt__2->SetBinContent(31,5);
   SubLeadingParticlePt__2->SetBinContent(32,1);
   SubLeadingParticlePt__2->SetBinContent(33,2);
   SubLeadingParticlePt__2->SetBinContent(35,1);
   SubLeadingParticlePt__2->SetBinContent(36,10);
   SubLeadingParticlePt__2->SetBinContent(37,11);
   SubLeadingParticlePt__2->SetBinContent(42,2);
   SubLeadingParticlePt__2->SetBinContent(46,8);
   SubLeadingParticlePt__2->SetBinContent(48,1);
   SubLeadingParticlePt__2->SetBinContent(50,1);
   SubLeadingParticlePt__2->SetEntries(199995);
   SubLeadingParticlePt__2->Scale(1./SubLeadingParticlePt__2->Integral());
   SubLeadingParticlePt__2->SetMarkerStyle(24);
   SubLeadingParticlePt__2->GetXaxis()->SetRange(4,64);
   SubLeadingParticlePt__2->GetXaxis()->SetLabelFont(42);
   SubLeadingParticlePt__2->GetXaxis()->SetTitleOffset(1);
   SubLeadingParticlePt__2->GetXaxis()->SetTitleFont(42);
   SubLeadingParticlePt__2->GetYaxis()->SetLabelFont(42);
   SubLeadingParticlePt__2->GetYaxis()->SetTitleFont(42);
   SubLeadingParticlePt__2->GetZaxis()->SetLabelFont(42);
   SubLeadingParticlePt__2->GetZaxis()->SetTitleOffset(1);
   SubLeadingParticlePt__2->GetZaxis()->SetTitleFont(42);
   SubLeadingParticlePt__2->Draw("EP SAME");
   
   TPaveText *pt = new TPaveText(0.1503006,0.9128205,0.8496994,0.9723077,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   pt->SetTextSize(0.02051282);
   TText *pt_LaTex = pt->AddText("Leading v Subleading p_{T} (No Quenching)");
   pt->Draw();
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
